config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to:"homes#top"

  resources :users,only: [:index,:show,:edit,:update,:create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books,only: [:index,:show,:edit,:update,:destroy,:create] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  # 通知機能
  resources :notifications, only: [:index,:destroy]

  get '/home/about' => 'homes#about',as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :subject, polymorphic: true
  belongs_to :user
  
  enum action_type: { commented_to_own_post: 0, liked_to_own_post: 1, followed_me: 3}
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.order(created_at: :desc).page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    @notifications = current_user.notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def transition_path(notification)
    case notification.action_type.to_sym
    when :commented_to_own_post
      post_book_path(notification.subject.post_book, anchor: "comment-#{notification.subject.id}")
    when :liked_to_own_post
      post_book_path(notification.subject.post_book)
    when :followed_me
      user_path(notification.subject.follower)
    end
  end
end

app/views/notifications/_commented_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.name, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_book_path(notification.subject.post_book) %>
    にコメントしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

app/views/notifications/_followed_me.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.follower.name, user_path(notification.subject.follower) %>
    があなたをフォローしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

app/views/notifications/_liked_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.name, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_book_path(notification.subject.book) %>
    にいいねしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

app/views/notifications/index.html.erb
<h4>通知</h4>
  <% if @notifications.present? %>
    <%= link_to "全削除",notification_path(@notifications), method: :delete,class:"btn btn-light" %>
    <% @notifications.each do |notification| %>
        <%= render "#{notification.action_type}", notification: notification %>
    <% end %>
  <% else %>
    通知はありません
  <% end %>