config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to:"homes#top"

  resources :users,only: [:index,:show,:edit,:update,:create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books,only: [:index,:show,:edit,:update,:destroy,:create] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  # 通知機能
  resources :notifications, only: [:index,:destroy]

  get '/home/about' => 'homes#about',as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  #フォローした、されたの関係
  has_many :to_follow, class_name:"Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :be_followed,class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  #一覧画面で使う
  has_many :followings, through: :to_follow, source: :followed
  has_many :followers, through: :be_followed, source: :follower
  #DM機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #閲覧数カウント
  has_many :read_counts, dependent: :destroy
  #通知機能
  has_many :notifications, dependent: :destroy


  validates :name,length: {in:2..20}, uniqueness: true
  validates :introduction,length: {maximum:400}

  has_one_attached :profile_image

  #フォロー機能
  def follow(user_id)
    to_follow.create(followed_id: user_id)
  end
  #フォローを外す時の処理
  def unfollow(user_id)
    to_follow.find_by(followed_id: user_id).destroy
  end
  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #  アクセス制限
  before_action :is_matching_login_user,only: [:edit,:update]
  before_action :authenticate_user!, only: [:show]



  def index
    @users=User.all
    @user=current_user
    @book=Book.new
    @books=Book.all
  end

  def show
    @user=User.find(params[:id])
    @books=@user.books.all
    @book=Book.new
    #DM機能
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

  def book_params
    params.require(:book).permit(:title,:body,:image)
  end

  def is_matching_login_user
    user=User.find(params[:id])
    unless user.id == current_user.id
      redirect_to current_user
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <% if user!=current_user %>
        <td><%= render 'relationships/btn', user: user %></td>
        <%else%>
        <td></td>
        <%end%>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <!--バリデーションメッセージ-->
      <div>
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <%end%>
        </ul>
      <%end%>
      </div>
      <%= form_with model:@user do |f| %>

      <div>
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus:true,id:"inputName",placeholder:"名前" %>
      </div>
      <div>
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image,placeholder:"プロフィール画像",accept:"image/*" %>
      </div>
      <div>
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_field :introduction, autofocus:true,id:"inputIntroduction" %>
      </div>
      <div>
        <%= f.submit "Update User",class: "btn btn-secondary" %>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--バリデーションメッセージ-->
<div>
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <%end%>
    </ul>
  <%end%>
</div>

<div class="container px-5 px-sm-0">
  <div class='row'>
    <%=render 'books/list',book: @book, user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--バリデーションメッセージ-->
<div>
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <%end%>
    </ul>
  <%end%>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <div>
        <%= image_tag @user.get_profile_image(100,100) %>
      </div>
      <table>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      <!--フォロー数、フォロワー数-->
        <tr>
          <th>follows</th>
          <th>
            <%= link_to user_followings_path(@user) do %>
              <%= @user.followings.count %>
            <%end%>
          </th>
        </tr>
        <tr>
          <th>followers</th>
          <th>
            <%= link_to user_followers_path(@user) do %>
              <%= @user.followers.count %>
            <%end%>
          </th>
        </tr>
      </table>
      <% if @user==current_user %>
      <div class="row">
        <%=link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-user-cog"></i>
        <%end%>
      </div>
      <%else%>
      <div class='row' >
        <% if current_user.following?(@user) %>
          <%= link_to "フォローを外す", user_relationships_path(@user.id), class: "btn btn-info btn-sm", method: :delete %>
        <%else%>
          <%= link_to "フォローをする", user_relationships_path(@user.id), class: "btn btn-success btn-sm", method: :post %>
        <%end%>
        <!--チャットボタン-->
        <% unless @user.id == current_user.id %>
          <% if (current_user.following? @user) && (@user.following? current_user)  %>
          <% if @isRoom == true %>
            <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
            <% end %>
          <% end %>
          <% end %>
        <% end %>
      </div>
      <%end%>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>

        <%= f.submit "Create Book",class: "btn btn-success" %>

      <%end%>
  </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_profile_image(80,80) %></td>
              <%end%>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <%end%>
            </td>
            <td><%= book.body %></td>
            <td><%= render 'book_comments/counter', book: @book %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>