config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to:"homes#top"

  resources :users,only: [:index,:show,:edit,:update,:create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books,only: [:index,:show,:edit,:update,:destroy,:create] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  # 通知機能
  resources :notifications, only: [:index,:destroy]

  get '/home/about' => 'homes#about',as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  #favoritesテーブルを介してUserモデルのコレクションを取得する
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments,dependent: :destroy
  #閲覧数カウント
  has_many :read_counts, dependent: :destroy
  
  has_one :notification, as: :subject, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title,presence: true
  validates :body,presence: true, length:{maximum:200}


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id

    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      @user=current_user
      render :index
    end
  end

  def index
    #fromからtoの期間に作成されたfavorites数に基づいて並び替える
    to=Time.current.at_end_of_day
    from=(to - 6.day).at_beginning_of_day
    @books=Book.includes(:favorited_users).
      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    @book=Book.new
    @user=current_user
  end

  def show
    @book=Book.find(params[:id])
    @book_new=Book.new
    @user=@book.user
    @books=@user.books.all
    @book_comment=BookComment.new
    @book_comments=BookComment.all
    #閲覧数カウント
    unless ReadCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.read_counts.create(book_id: @book.id)
    end
  end

  def edit
    is_matching_login_user
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:image)
  end

  def is_matching_login_user

    book=Book.find(params[:id])

    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_iine.html.erb
<% if book.favorited_by?(current_user) %>
  <%=link_to book_favorites_path(book),method: :delete, remote: true do %>
    <i class="fas fa-heart" style="color:red;"></i><%= book.favorites.count %>
  <%end%>
<%else%>
  <%=link_to book_favorites_path(book),method: :post, remote: true do %>
    <i class="far fa-heart" style="color:blue;"></i><%= book.favorites.count %>
  <%end%>
<%end%>

app/views/books/_list.html.erb
  <div class="col-md-3">
      <h2>User info</h2>
      <div>
        <%= image_tag user.get_profile_image(100,100) %>
      </div>

      <table>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      <!--フォロー数、フォロワー数-->
        <tr>
          <th>follows</th>
          <th>
            <%= link_to user_followings_path(user) do %>
              <%= user.followings.count %>
            <%end%>
          </th>
        </tr>
        <tr>
          <th>followers</th>
          <th>
            <%= link_to user_followers_path(user) do %>
              <%= user.followers.count %>
            <%end%>
          </th>
        </tr>
      </table>
      <% if user==current_user %>
      <div class="row">
        <%=link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-user-cog"></i>
        <%end%>
      </div>
      <%else%>
      <div class='row' >
        <% if current_user.following?(user) %>
          <%= link_to "フォローを外す", user_relationships_path(user.id), class: "btn btn-info btn-sm", method: :delete %>
        <%else%>
          <%= link_to "フォローをする", user_relationships_path(user.id), class: "btn btn-success btn-sm", method: :post %>
        <%end%>
        <!--DM機能-->
        
      </div>
      <%end%>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>

        <%= f.submit "Create Book",class: "btn btn-success" %>

      <%end%>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <!--バリデーションメッセージ-->
      <div>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <%end%>
        </ul>
      <%end%>
      </div>

      <%= form_with model: @book do |f| %>
      <div>
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, autofocus:true,id:"inputTitle" %>
      </div>
      <div>
        <label for="inputOpinion">Opinion</label>
        <%= f.text_field :body, autofocus:true,id:"inputOpinion" %>
      </div>
      <div>
        <%= f.submit "Update Book",class: "btn btn-success" %>
      </div>
      <%end%>
      <%= link_to book_path do %>
      Show
      <%end%>
       |
       <%= link_to books_path do %>
      Back
      <%end%>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<!--バリデーションメッセージ-->
<div>
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <%end%>
    </ul>
  <%end%>
</div>

<div class="container px-5 px-sm-0">
  <div class='row'>
    <%=render 'list',book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <%end%>
            </td>
            <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <%end%>
            </td>
            <td><%= book.body %></td>
            <!--いいね機能-->
            <td id="favorite_buttons_<%= book.id %>"><%= render 'iine', book: book %></td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--バリデーションメッセージ-->
<div>
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <%end%>
    </ul>
  <%end%>
</div>

<div class="container px-5 px-sm-0">
  <div class='row'>
    <%=render 'list',book: @book_new, user: @user %>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table>
        <tbody>

          <tr>
            <td>
              <%=link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(80,80) %>
                <%= @book.user.name %>
              <%end%>
            </td>
            <td>
              <%=link_to book_path(@book.id) do %>
                <%= @book.title %>
              <%end%>
            </td>
            <td><%= @book.body %></td>
            <td id="favorite_buttons_<%= @book.id %>">
              <%= render 'iine', book: @book %>
            </td>
            <td id="comment_counter">
              <%= render 'book_comments/counter', book: @book %>
            </td>
            <td>閲覧数: <%= @book.read_counts.count %></td>
            <% if @book.user==current_user %>
            <td>
              <%=link_to "Edit",edit_book_path(@book), class:"btn btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy",book_path(@book), method: :delete,"data-confirm"=>"本当に消しますか？", class:"btn btn-sm btn-danger" %>
            </td>
            <%end%>
          </tr>

        </tbody>
      </table>
      <!--コメント一覧-->
      <div id="comments_index">
        <%= render 'book_comments/index', book: @book %>
      </div>
      <!--コメント投稿機能-->
      <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>