config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to:"homes#top"

  resources :users,only: [:index,:show,:edit,:update,:create] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books,only: [:index,:show,:edit,:update,:destroy,:create] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  # 通知機能
  resources :notifications, only: [:index,:destroy]

  get '/home/about' => 'homes#about',as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  #favoritesテーブルを介してUserモデルのコレクションを取得する
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments,dependent: :destroy
  #閲覧数カウント
  has_many :read_counts, dependent: :destroy
  
  has_one :notification, as: :subject, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title,presence: true
  validates :body,presence: true, length:{maximum:200}


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  has_one :notification, as: :subject, dependent: :destroy
  after_create_commit :create_notifications

  validates :comment,presence:true
  
  private
  def create_notifications
    Notification.create(subject: self, end_user: post_workout.end_user, action_type: :commented_to_own_post)
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  has_one :notification, as: :subject, dependent: :destroy
  after_create_commit :create_notifications

  validates :user_id,uniqueness: {scope: :book_id}
  
  private
  def create_notifications
    Notification.create(subject: self, user: self.post_workout.user, action_type: :liked_to_own_post)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :message, presence: true, length: {maximum: 140}
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :subject, polymorphic: true
  belongs_to :user
  
  enum action_type: { commented_to_own_post: 0, liked_to_own_post: 1, followed_me: 3}
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  has_one :notification, as: :subject, dependent: :destroy
  after_create_commit :create_notifications

  private
  def create_notifications
    Notification.create(subject: self, user: followed, action_type: :followed_me)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  #フォローした、されたの関係
  has_many :to_follow, class_name:"Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :be_followed,class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  #一覧画面で使う
  has_many :followings, through: :to_follow, source: :followed
  has_many :followers, through: :be_followed, source: :follower
  #DM機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #閲覧数カウント
  has_many :read_counts, dependent: :destroy
  #通知機能
  has_many :notifications, dependent: :destroy


  validates :name,length: {in:2..20}, uniqueness: true
  validates :introduction,length: {maximum:400}

  has_one_attached :profile_image

  #フォロー機能
  def follow(user_id)
    to_follow.create(followed_id: user_id)
  end
  #フォローを外す時の処理
  def unfollow(user_id)
    to_follow.find_by(followed_id: user_id).destroy
  end
  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id

    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      @user=current_user
      render :index
    end
  end

  def index
    #fromからtoの期間に作成されたfavorites数に基づいて並び替える
    to=Time.current.at_end_of_day
    from=(to - 6.day).at_beginning_of_day
    @books=Book.includes(:favorited_users).
      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    @book=Book.new
    @user=current_user
  end

  def show
    @book=Book.find(params[:id])
    @book_new=Book.new
    @user=@book.user
    @books=@user.books.all
    @book_comment=BookComment.new
    @book_comments=BookComment.all
    #閲覧数カウント
    unless ReadCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.read_counts.create(book_id: @book.id)
    end
  end

  def edit
    is_matching_login_user
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:image)
  end

  def is_matching_login_user

    book=Book.find(params[:id])

    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--FontAwesomeの導入-->
    <script src="https://kit.fontawesome.com/c6b38ceb92.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                       aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse " id="navbarNavDropdown" >
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <!--通知機能-->
              <li>
                <%= link_to notifications_path, class: "nav-link text-light" do %>
                <i class="fas fa-bell"></i>通知
                <% end %>
              </li>
              <li>
                <%=link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
                <%end%>
              </li>
              <li>
                <%=link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>Users
                <%end%>
              </li>
              <li>
                <%=link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>Books
                <%end%>
              </li>
              <li>
                <%=link_to destroy_user_session_path,method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>Log out
                <%end%>
              </li>

            <% else %>
              <li>
                <%=link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
                <%end%>
              </li>
              <li>
                <%=link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>About
                <%end%>
              </li>
              <li>
                <%=link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>Sign up
                <%end%>
              </li>
              <li>
                <%=link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>Log in
                <%end%>
              </li>
            <%end%>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <!--フラッシュメッセージ-->
      <div id="notice">
        <%= flash[:notice] %>
      </div>

    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>